name: Streaming list update

on: 
  push:
      
  schedule:
    - cron: '0 */2 * * * '
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Github Action gen-sh-unittest
      id: action-gen-sh-unittest
      uses: vargiuscuola/gen-sh-unittest@master
    - name: gensh-unittest result
      run: echo "The result of gensh-unittest Action was ${{ steps.action-gen-sh-unittest.outputs.result }}"
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        wget https://raw.githubusercontent.com/alexcha/music/main/get_list.sh
        export LANG=ko_KR
       
        chmod +x get_list.sh
        
         ./get_list.sh > list.pls
         sed -i '/^\s*$/d' list.pls
          git add list.pls
          
          git config --local user.name "alexcha"
          git commit -m "new date commit"
          git branch -M main
          git push origin main | exit 0
          
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MUSIC_KEY }}
