name: alex
on: push

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: http://saycast.sayclub.com/saycast/index/station?kind=genrelist&catGenre=mTR&page=2
