name: alex
on: push

jobs:
  linux:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1



    - name: Moving build to artifacts directory
      run: ./scripts/get_list.sh
